raw_data_path = './input/iptv_new_zxrecord_20180418.txt'# 原文件
processed_path = './processed_data' # 处理之后的文件
cleaned_path = processed_path + '/cleaned_data.csv' # 清洗之后的数据
text_info_path = './text_info/text_info.csv' # 节目对应的标签
result_path = './result'# 结果
cluster_result_path = result_path + '/cluster_result.pkl'# 聚类结果
week_data_path = './input/2026'
xls_path = './xlsx'
cluster_xls_result = './xlsx/cluster_result.xlsx'
recommend_xls_result = './xlsx/recommend_result.xlsx'